server:
  port: 8083

spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: inventory-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.inventoryservice.model,com.example.orderservice.model,com.example.paymentservice.model

logging:
  level:
    com.example.inventoryservice: INFO
    org.springframework.kafka: INFO