server:
  port: 8082

spring:
  application:
    name: payment-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.paymentservice.model,com.example.orderservice.model

logging:
  level:
    com.example.paymentservice: INFO
    org.springframework.kafka: INFO