spring:
  config:
    activate:
      on-profile: tcc
  application:
    name: account-service-tcc

seata:
  enabled: ${SEATA_ENABLED:true}
  application-id: ${SEATA_APPLICATION_ID:account-service-tcc}
  tx-service-group: ${SEATA_TX_SERVICE_GROUP:tcc_tx_group}
  service:
    vgroup-mapping:
      tcc_tx_group: ${SEATA_VGROUP_MAPPING_TCC_TX_GROUP:default}
#      default_tx_group: ${SEATA_VGROUP_MAPPING_DEFAULT_TX_GROUP:default}
    grouplist:
      default: ${SEATA_GROUPLIST_DEFAULT:127.0.0.1:8091}
  registry:
    type: ${SEATA_REGISTRY_TYPE:file}
  config:
    type: ${SEATA_CONFIG_TYPE:file}
#  enable-auto-data-source-proxy: ${SEATA_ENABLE_AUTO_DATA_SOURCE_PROXY:true}
  enable-auto-data-source-proxy: false
#  data-source-proxy-mode: ${SEATA_DATA_SOURCE_PROXY_MODE:AT}
