spring:
  application:
    name: account-service-at
  datasource:
    url: jdbc:mysql://localhost:3307/seata_account?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
      minimum-idle: 0
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: false
logging:
  level:
    root: INFO

# Register initializer to load .env, .env-<profile>, or ENV_FILE
context:
  initializer:
    classes: com.example.seata.common.config.DotenvInitializer

seata:
  enabled: ${SEATA_ENABLED:true}
  application-id: ${SEATA_APPLICATION_ID:account-service-at}
  tx-service-group: ${SEATA_TX_SERVICE_GROUP:at_tx_group}
  service:
    vgroup-mapping:
      at_tx_group: ${SEATA_VGROUP_MAPPING_AT_TX_GROUP:default}
    grouplist:
      default: ${SEATA_GROUPLIST_DEFAULT:127.0.0.1:8091}
  registry:
    type: ${SEATA_REGISTRY_TYPE:file}
  config:
    type: ${SEATA_CONFIG_TYPE:file}
  #  registry:
  #    type: nacos
  #    nacos:
  #      server-addr: 127.0.0.1:8848
  #      namespace: ""                 # 必要ならNacosのnamespace IDを設定
  #      group: SEATA_GROUP
  #  config:
  #    type: nacos
  #    nacos:
  #      server-addr: 127.0.0.1:8848
  #      namespace: ""                 # 必要ならNacosのnamespace IDを設定
  #      group: SEATA_GROUP
  enable-auto-data-source-proxy: ${SEATA_ENABLE_AUTO_DATA_SOURCE_PROXY:true}
  data-source-proxy-mode: ${SEATA_DATA_SOURCE_PROXY_MODE:AT}
