spring:
  application:
    name: account-service-at
  datasource:
    url: jdbc:mysql://localhost:3307/seata_account?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: -1
      minimum-idle: 0
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: false
logging:
  level:
    root: INFO

seata:
  enabled: true
  application-id: account-service-at
  tx-service-group: at_tx_group
  service:
    vgroup-mapping:
      at_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
  registry:
    type: file
  config:
    type: file
  #  registry:
  #    type: nacos
  #    nacos:
  #      server-addr: 127.0.0.1:8848
  #      namespace: ""                 # 必要ならNacosのnamespace IDを設定
  #      group: SEATA_GROUP
  #  config:
  #    type: nacos
  #    nacos:
  #      server-addr: 127.0.0.1:8848
  #      namespace: ""                 # 必要ならNacosのnamespace IDを設定
  #      group: SEATA_GROUP
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
