spring:
  config:
    activate:
      on-profile: at
  application:
    name: order-service-at

seata:
  enabled: ${SEATA_ENABLED:true}
  application-id: ${SEATA_APPLICATION_ID:order-service-at}
  tx-service-group: ${SEATA_TX_SERVICE_GROUP:at_tx_group}
  service:
    vgroup-mapping:
      at_tx_group: ${SEATA_VGROUP_MAPPING_AT_TX_GROUP:default}
      default_tx_group: ${SEATA_VGROUP_MAPPING_DEFAULT_TX_GROUP:default}
    grouplist:
      default: ${SEATA_GROUPLIST_DEFAULT:127.0.0.1:8091}
  registry:
    type: ${SEATA_REGISTRY_TYPE:file}
  config:
    type: ${SEATA_CONFIG_TYPE:file}
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
